// Generated by CoffeeScript 1.9.3
(function() {
  var recursiveDelete;

  recursiveDelete = function(children) {
    var child, i, len;
    for (i = 0, len = children.length; i < len; i++) {
      child = children[i];
      if (require.cache[child.id]) {
        children = require.cache[child.id].children;
        delete require.cache[child.id];
        if (children != null) {
          recursiveDelete(children);
        }
      }
    }
    return null;
  };

  module.exports = function(name, deep) {
    var fullname;
    if (deep == null) {
      deep = false;
    }
    fullname = require.resolve(name);
    if (require.cache[fullname]) {
      if (deep) {
        recursiveDelete(require.cache[fullname].children);
      }
      delete require.cache[fullname];
    }
    return require(fullname);
  };

}).call(this);
